server:
  port: 8080

grpc:
  server:
    port: 9090        # gRPC will run on port 9090
    in-process-name: gateway-grpc
    security:
      enabled: false  # disable SSL for local testing

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # Automatically map services from Eureka
          lower-case-service-id: true
      routes:
        # Optional manual routes (for clarity or path rewrite)
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/** # Match paths starting with /api/users/
          filters:
            - RewritePath=/api/users/(?<path>.*), /${path}

        - id: todo-service
          uri: lb://todo-service
          predicates:
            - Path=/api/todos/**
          filters:
            - RewritePath=/api/todos/(?<path>.*), /${path}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/,http://localhost:8763/eureka/
  instance:
    prefer-ip-address: true
