services:
  todo-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: todo-application
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SERVER_PORT=8080
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    restart: unless-stopped
    networks:
      - todo-network

  # Optional: If you want to use PostgreSQL instead of H2
  # postgres:
  #   image: postgres:15-alpine
  #   container_name: todo-postgres
  #   environment:
  #     POSTGRES_DB: tododb
  #     POSTGRES_USER: todouser
  #     POSTGRES_PASSWORD: todopass
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   networks:
  #     - todo-network

networks:
  todo-network:
    driver: bridge

# volumes:
#   postgres_data: