server:
    port: 8762

spring:
    application:
        name: eureka-server

eureka:
    instance:
        hostname: eureka-server-b
    client:
        register-with-eureka: true
        fetch-registry: true
        service-url:
            defaultZone: http://eureka-server-a:8761/eureka/,http://eureka-server-c:8763/eureka/
