// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: voice.proto

package voice_proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	VoiceStream_StreamText_FullMethodName = "/voice.VoiceStream/StreamText"
)

// VoiceStreamClient is the client API for VoiceStream service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type VoiceStreamClient interface {
	StreamText(ctx context.Context, in *VoiceRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[VoiceText], error)
}

type voiceStreamClient struct {
	cc grpc.ClientConnInterface
}

func NewVoiceStreamClient(cc grpc.ClientConnInterface) VoiceStreamClient {
	return &voiceStreamClient{cc}
}

func (c *voiceStreamClient) StreamText(ctx context.Context, in *VoiceRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[VoiceText], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &VoiceStream_ServiceDesc.Streams[0], VoiceStream_StreamText_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[VoiceRequest, VoiceText]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type VoiceStream_StreamTextClient = grpc.ServerStreamingClient[VoiceText]

// VoiceStreamServer is the server API for VoiceStream service.
// All implementations must embed UnimplementedVoiceStreamServer
// for forward compatibility.
type VoiceStreamServer interface {
	StreamText(*VoiceRequest, grpc.ServerStreamingServer[VoiceText]) error
	mustEmbedUnimplementedVoiceStreamServer()
}

// UnimplementedVoiceStreamServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedVoiceStreamServer struct{}

func (UnimplementedVoiceStreamServer) StreamText(*VoiceRequest, grpc.ServerStreamingServer[VoiceText]) error {
	return status.Errorf(codes.Unimplemented, "method StreamText not implemented")
}
func (UnimplementedVoiceStreamServer) mustEmbedUnimplementedVoiceStreamServer() {}
func (UnimplementedVoiceStreamServer) testEmbeddedByValue()                     {}

// UnsafeVoiceStreamServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VoiceStreamServer will
// result in compilation errors.
type UnsafeVoiceStreamServer interface {
	mustEmbedUnimplementedVoiceStreamServer()
}

func RegisterVoiceStreamServer(s grpc.ServiceRegistrar, srv VoiceStreamServer) {
	// If the following call pancis, it indicates UnimplementedVoiceStreamServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&VoiceStream_ServiceDesc, srv)
}

func _VoiceStream_StreamText_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(VoiceRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(VoiceStreamServer).StreamText(m, &grpc.GenericServerStream[VoiceRequest, VoiceText]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type VoiceStream_StreamTextServer = grpc.ServerStreamingServer[VoiceText]

// VoiceStream_ServiceDesc is the grpc.ServiceDesc for VoiceStream service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VoiceStream_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "voice.VoiceStream",
	HandlerType: (*VoiceStreamServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamText",
			Handler:       _VoiceStream_StreamText_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "voice.proto",
}
