// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: voice.proto

package voice_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VoiceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VoiceRequest) Reset() {
	*x = VoiceRequest{}
	mi := &file_voice_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VoiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VoiceRequest) ProtoMessage() {}

func (x *VoiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_voice_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VoiceRequest.ProtoReflect.Descriptor instead.
func (*VoiceRequest) Descriptor() ([]byte, []int) {
	return file_voice_proto_rawDescGZIP(), []int{0}
}

func (x *VoiceRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type VoiceText struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Part          int32                  `protobuf:"varint,2,opt,name=part,proto3" json:"part,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VoiceText) Reset() {
	*x = VoiceText{}
	mi := &file_voice_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VoiceText) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VoiceText) ProtoMessage() {}

func (x *VoiceText) ProtoReflect() protoreflect.Message {
	mi := &file_voice_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VoiceText.ProtoReflect.Descriptor instead.
func (*VoiceText) Descriptor() ([]byte, []int) {
	return file_voice_proto_rawDescGZIP(), []int{1}
}

func (x *VoiceText) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *VoiceText) GetPart() int32 {
	if x != nil {
		return x.Part
	}
	return 0
}

var File_voice_proto protoreflect.FileDescriptor

const file_voice_proto_rawDesc = "" +
	"\n" +
	"\vvoice.proto\x12\x05voice\"-\n" +
	"\fVoiceRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"3\n" +
	"\tVoiceText\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x12\n" +
	"\x04part\x18\x02 \x01(\x05R\x04part2D\n" +
	"\vVoiceStream\x125\n" +
	"\n" +
	"StreamText\x12\x13.voice.VoiceRequest\x1a\x10.voice.VoiceText0\x01B\"Z genproto/voice_proto;voice_protob\x06proto3"

var (
	file_voice_proto_rawDescOnce sync.Once
	file_voice_proto_rawDescData []byte
)

func file_voice_proto_rawDescGZIP() []byte {
	file_voice_proto_rawDescOnce.Do(func() {
		file_voice_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_voice_proto_rawDesc), len(file_voice_proto_rawDesc)))
	})
	return file_voice_proto_rawDescData
}

var file_voice_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_voice_proto_goTypes = []any{
	(*VoiceRequest)(nil), // 0: voice.VoiceRequest
	(*VoiceText)(nil),    // 1: voice.VoiceText
}
var file_voice_proto_depIdxs = []int32{
	0, // 0: voice.VoiceStream.StreamText:input_type -> voice.VoiceRequest
	1, // 1: voice.VoiceStream.StreamText:output_type -> voice.VoiceText
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_voice_proto_init() }
func file_voice_proto_init() {
	if File_voice_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_voice_proto_rawDesc), len(file_voice_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_voice_proto_goTypes,
		DependencyIndexes: file_voice_proto_depIdxs,
		MessageInfos:      file_voice_proto_msgTypes,
	}.Build()
	File_voice_proto = out.File
	file_voice_proto_goTypes = nil
	file_voice_proto_depIdxs = nil
}
